[versions]
kotlin = "2.3.0-RC2"
kotlinx-serialization = "1.9.0"
quickMpp = "0.21"
jmh = "1.37"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
androidx-collection = { module = "androidx.collection:collection", version = "1.5.0" }
objectPool = { module = "io.github.adokky:object-pool", version = "1.0" }
bitvector = { module = "io.github.adokky:bitvector", version = "0.9.2" }
equalsTester = { module = "io.github.adokky:equals-tester", version = "1.1.0" }
karamelUtils-core = { module = "io.github.adokky:karamel-utils-core", version = "0.2.0" }
karamelUtils-tsbits = { module = "io.github.adokky:karamel-utils-ts-bits", version = "0.1.1" }
kodec-struct = { module = "io.github.adokky:kodec-struct", version = "0.2.1" }
kodec-strings-stream = { module = "io.github.adokky:kodec-strings-stream", version = "0.8.9" }
kodec-strings-common = { module = "io.github.adokky:kodec-strings-common", version = "0.1.2" }
kodec-strings-utf = { module = "io.github.adokky:kodec-strings-utf", version = "0.3.8" }
jmh-processor = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }

[plugins]
jmh = { id = "me.champeau.jmh", version = "0.7.3" }
quick-mpp = { id = "io.github.adokky.quick-mpp", version.ref = "quickMpp" }
quick-jvm = { id = "io.github.adokky.quick-jvm", version.ref = "quickMpp" }
quick-publish = { id = "io.github.adokky.quick-publish", version.ref = "quickMpp" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }